//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAD7_Project_MovieDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieRating
    {
        public int RatingID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public int Rating { get; set; }
    }
}
